### PR TITLE
Combo footprint

### PR DESCRIPTION
**Pull request by gcormier**
Per #1 . Still needs updated pictures.

### CODE REVIEW

**Comment by sirhcel** [comment]
Awesome! Thank you for this contribution. I've updated board rendering and `README.md` as of https://github.com/sirhcel/dl3000-adapters/commit/bece12cf235554b425969436f1943a4eb0b4b954. Comparing the Gerber files looks good and I've also ordered some updated boards at OSH Park.

Are there pictures left, you want to update?

I'm expecting the boards to just work as expected and if you confirm this, let's have the update integrated into _master_.

**Comment by gcormier** [comment]
Lol, well, that didn't work. These part numbers are tiny! 2mm banana jacks. Back to the drawing board and another order from JLC I guess :)

**Comment by gcormier** [comment]
Going to close as this is no good :(

**Comment by sirhcel** [comment]
What a pitty! I didn't spot this issue neither. :( Let's go back to square #1.

**Pull request closed without merging**
